In [44]:
import torch 
import torch.nn.functional as F
import matplotlib.pyplot as plt 
%matplotlib inline 

In [45]:
words = open('data/names.txt','r').read().splitlines()
words[:10], len(words)

(['emma',
  'olivia',
  'ava',
  'isabella',
  'sophia',
  'charlotte',
  'mia',
  'amelia',
  'harper',
  'evelyn'],
 32033)

In [46]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] =0 
itos = {i:s for s,i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [ ]:
block_size = 3
X,Y =[],[] #X input and Y is the label
for w in words[:5]:
    print(w)
    context = [0]*block_size
    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        print(''.join(itos[i] for i in context),'--->',itos[ix])
        context = context[1:] + [ix]

X = torch.tensor(X)
Y = torch.tensor(Y)


emma
... ---> e
..e ---> m
.em ---> m
emm ---> a
mma ---> .
olivia
... ---> o
..o ---> l
.ol ---> i
oli ---> v
liv ---> i
ivi ---> a
via ---> .
ava
... ---> a
..a ---> v
.av ---> a
ava ---> .
isabella
... ---> i
..i ---> s
.is ---> a
isa ---> b
sab ---> e
abe ---> l
bel ---> l
ell ---> a
lla ---> .
sophia
... ---> s
..s ---> o
.so ---> p
sop ---> h
oph ---> i
phi ---> a
hia ---> .


In [48]:
X.shape, X.dtype, Y.shape, Y.dtype

(torch.Size([32, 3]), torch.int64, torch.Size([32]), torch.int64)

In [73]:
Y.shape

torch.Size([32])

In [51]:
C = torch.randn((27,2) )
C

tensor([[ 2.5591e-01, -2.0169e+00],
        [-3.9368e-01, -5.2913e-01],
        [-4.5141e-04,  1.2309e+00],
        [ 7.7141e-01,  8.1153e-01],
        [-9.7200e-01, -1.9791e+00],
        [ 1.2032e+00,  8.5447e-02],
        [ 4.3344e-01, -1.2762e-01],
        [ 7.8659e-02,  1.2573e+00],
        [-1.5896e+00,  1.4136e+00],
        [ 9.8831e-01, -6.3891e-02],
        [-1.0658e+00,  8.0101e-01],
        [ 2.0402e+00, -1.0683e+00],
        [ 1.7120e+00,  1.8968e+00],
        [ 4.7411e-01, -1.5038e+00],
        [ 5.3543e-01,  1.2219e-01],
        [-1.5202e+00, -1.5436e+00],
        [-1.7641e+00, -1.8772e-01],
        [ 6.4437e-01, -4.6225e-01],
        [ 7.3646e-01, -1.9844e+00],
        [-1.1428e-02, -1.8024e+00],
        [ 5.3099e-01,  8.5269e-01],
        [ 6.8807e-02,  5.7087e-01],
        [-2.2469e+00,  1.1453e+00],
        [ 3.5423e-01,  1.3300e-01],
        [ 1.6915e-01, -9.8264e-01],
        [-7.9924e-02, -3.9849e-01],
        [ 1.6117e+00, -1.0394e+00]])

In [52]:
#cramping into 27 chracters to 2 dimentions 
C[5]

tensor([1.2032, 0.0854])

In [55]:
F.one_hot(torch.tensor(5),num_classes=27).float() @ C

tensor([1.2032, 0.0854])

In [57]:
F.one_hot(torch.tensor(5),num_classes=27).float() @ C

tensor([1.2032, 0.0854])

In [59]:
C[5]

tensor([1.2032, 0.0854])

In [62]:
C[torch.tensor([5,6,7,7,7,7])]

tensor([[ 1.2032,  0.0854],
        [ 0.4334, -0.1276],
        [ 0.0787,  1.2573],
        [ 0.0787,  1.2573],
        [ 0.0787,  1.2573],
        [ 0.0787,  1.2573]])

In [63]:
C.shape

torch.Size([27, 2])

In [65]:
C[X].shape

torch.Size([32, 3, 2])

In [ ]:
C[X]

tensor([[ 0.2559, -2.0169],
        [ 0.2559, -2.0169],
        [ 0.2559, -2.0169]])

In [67]:
X[13,2]

tensor(1)

In [68]:
C[X][13,2]

tensor([-0.3937, -0.5291])

In [71]:
emb = C[X]
emb.shape

torch.Size([32, 3, 2])

In [77]:
W1 = torch.randn((6,100))
b1 = torch.randn(100)



In [84]:
h = torch.tanh(emb.view(-1,6) @ W1 + b1)
h.shape

torch.Size([32, 100])

In [ ]:
W2 = torch.randn((100,27)) 
b2 = torch.randn(27)

In [83]:
logits = h @ W2 + b2
logits.shape

torch.Size([32, 27])

In [89]:
counts = logits.exp()
prob = counts/counts.sum(1,keepdim=True)
prob.shape

torch.Size([32, 27])

In [93]:
prob[1]

tensor([9.8499e-01, 2.8605e-10, 8.7001e-11, 5.4483e-08, 6.4232e-12, 4.8900e-12,
        3.7024e-14, 4.5847e-11, 6.2552e-15, 1.7096e-12, 1.4427e-15, 1.4263e-05,
        1.6022e-11, 3.2100e-10, 1.5124e-11, 1.8597e-12, 9.4604e-08, 4.2007e-06,
        1.8064e-15, 1.3934e-02, 5.1642e-09, 3.9483e-13, 1.0452e-03, 5.3489e-07,
        2.3251e-10, 1.2579e-07, 1.2991e-05])

In [106]:
num = len(X)

loss = -prob[torch.arange(num),Y].log().mean()
print(loss.item())
W1.grad = None 
b1.grad = None 

W2.grad= None 
b2.grad = None 


18.62990951538086


In [98]:
prob[torch.arange(num),Y]

tensor([7.9367e-09, 3.2100e-10, 2.6263e-10, 1.5750e-02, 9.2797e-02, 8.1526e-11,
        4.1075e-03, 6.2557e-13, 9.4007e-12, 8.9225e-10, 4.4555e-16, 2.0311e-11,
        2.1904e-01, 1.9513e-01, 2.0759e-09, 2.0596e-19, 1.5517e-13, 3.9078e-02,
        8.7320e-02, 2.4377e-01, 3.3139e-07, 7.8770e-11, 2.0713e-13, 1.3163e-09,
        3.6571e-17, 2.9571e-01, 7.6025e-11, 2.9086e-10, 2.4166e-08, 4.9933e-09,
        4.9828e-11, 3.2946e-13])

In [107]:
X.shape, Y.shape

(torch.Size([32, 3]), torch.Size([32]))

In [150]:
g = torch.Generator().manual_seed(2147483647)
C = torch.randn((27,2), generator=g)
W1 = torch.randn((6,100),generator=g)
b1 = torch.randn(100, generator=g)
W2 = torch.randn((100,27),generator=g)
b2 = torch.randn(27, generator=g)
parameters = [C,W1,b1,W2,b2]

for p in parameters:
    p.requires_grad = True

In [153]:
for _ in range(1000):
    #forward pass
    emb = C[X]
    h = torch.tanh(emb.view(-1,6)@W1+b1)
    logits = h @ W2 + b2 
    # counts = logits.exp()
    # prob = counts / counts.sum(dim=1, keepdim=True)
    # loss = - prob[torch.arange(32), Y].log().mean()
    loss =F.cross_entropy(logits,Y)
    #print(loss.item())
    

    for p in parameters:
        p.grad = None
    loss.backward()

    for p in parameters:
        p.data += -0.1*p.grad

print(loss.item())

0.25285276770591736
